spring:
  datasource:
    username: rattery
    password: rattery
    url: jdbc:mysql://localhost:3306/rattery
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  sql:
    init:
      mode: never