INSERT INTO variety (variety_type) VALUES ('Top-Eared');
INSERT INTO variety (variety_type) VALUES ('Dumbo-Eared');
INSERT INTO variety (variety_type) VALUES ('Black-Eyed');
INSERT INTO variety (variety_type) VALUES ('Pink/Red-Eyed');
INSERT INTO variety (variety_type) VALUES ('Ruby-Eyed');
INSERT INTO variety (variety_type) VALUES ('Odd-Eyed');
INSERT INTO variety (variety_type) VALUES ('Harley');
INSERT INTO variety (variety_type) VALUES ('Bristle');
INSERT INTO variety (variety_type) VALUES ('Hairless/Double Rex');
INSERT INTO variety (variety_type) VALUES ('Normal/Standard');
INSERT INTO variety (variety_type) VALUES ('Rex');
INSERT INTO variety (variety_type) VALUES ('Satin/Silky');
INSERT INTO variety (variety_type) VALUES ('Velveteen');
INSERT INTO variety (variety_type) VALUES ('Mink');
INSERT INTO variety (variety_type) VALUES ('Black');
INSERT INTO variety (variety_type) VALUES ('White');
INSERT INTO variety (variety_type) VALUES ('Champagne');
INSERT INTO variety (variety_type) VALUES ('Dove');
INSERT INTO variety (variety_type) VALUES ('Lilac');
INSERT INTO variety (variety_type) VALUES ('Blue');
INSERT INTO variety (variety_type) VALUES ('Powder Blue');
INSERT INTO variety (variety_type) VALUES ('Agouti');
INSERT INTO variety (variety_type) VALUES ('Cinnamon');
INSERT INTO variety (variety_type) VALUES ('Blue Agouti');
INSERT INTO variety (variety_type) VALUES ('Argente');
INSERT INTO variety (variety_type) VALUES ('Fawn');
INSERT INTO variety (variety_type) VALUES ('Silvermane');
INSERT INTO variety (variety_type) VALUES ('Self');
INSERT INTO variety (variety_type) VALUES ('Hooded');
INSERT INTO variety (variety_type) VALUES ('Caped/Bareback');
INSERT INTO variety (variety_type) VALUES ('Variegated');
INSERT INTO variety (variety_type) VALUES ('Dalmation');
INSERT INTO variety (variety_type) VALUES ('Berkshire');
INSERT INTO variety (variety_type) VALUES ('Irish/English Irish');
INSERT INTO variety (variety_type) VALUES ('Blazed');
INSERT INTO variety (variety_type) VALUES ('Downunder (DU)');
INSERT INTO variety (variety_type) VALUES ('DU Berkshire');
INSERT INTO variety (variety_type) VALUES ('DU Spotted');
INSERT INTO variety (variety_type) VALUES ('Himalayan');
INSERT INTO variety (variety_type) VALUES ('Siamese');
INSERT INTO variety (variety_type) VALUES ('Manx');
